### ISSUE TITLE
My Patcher won't let me patch

### ISSUE THREAD

**Issue by RedLazer5000** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#103]
I am attempting to Patch TS1, but it let me Patch it. It greys out the Patch button no matter what I do. Can someone help me?

**Comment by Pixel946** [comment]
I had this problem too. The problem appears to be that I was trying to patch the original .exe file instead of the cracked one. This may be the issue you're having as well?

**Comment by FaithBeam** [comment]
@RedLazer5000  and @Pixel946
It's because you are either not using a cracked sims exe or you're using a cracked sims exe that has already been patched to a custom resolution and does not have a backup. The solution is to download a cracked sims exe that has not been patched to a custom resolution. 

I've added a popup notification in 3.13.0 with this information so there will be no confusion in the future.
