### ISSUE TITLE
Error on open wont work

### ISSUE THREAD

**Issue by samboa86** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#12]
I get an error just trying to open the file. I run as admin. the error I get :
an unhandled exception occured: the invocation of the constructor  on type 'HexEditApp.MainWindow' that matched the specified binding constraints threw an exception."

I tried changing the directory to C and did it again, no luck.

the log shows:

2020-08-15 20:05:29,811 [1] INFO HexEditApp.App - =============  Started Logging  =============
2020-08-15 20:05:29,829 [1] INFO HexEditApp.App - 1.16.0.0
2020-08-15 20:05:29,829 [1] INFO HexEditApp.App - Microsoft Windows NT 6.2.9200.0
2020-08-15 20:05:29,830 [1] INFO HexEditApp.App - Base directory: I:\Program Files (x86)\Maxis\
2020-08-15 20:05:29,831 [1] INFO HexEditApp.App - Current directory: I:\Program Files (x86)\Maxis
2020-08-15 20:05:30,008 [1] ERROR HexEditApp.MainWindow - An unhandled exception occurred: The invocation of the constructor on type 'HexEditApp.MainWindow' that matches the specified binding constraints threw an exception.
2020-08-15 20:07:58,942 [1] INFO HexEditApp.App - =============  Started Logging  =============
2020-08-15 20:07:58,953 [1] INFO HexEditApp.App - 1.16.0.0
2020-08-15 20:07:58,953 [1] INFO HexEditApp.App - Microsoft Windows NT 6.2.9200.0
2020-08-15 20:07:58,954 [1] INFO HexEditApp.App - Base directory: C:\Program Files (x86)\Maxis\
2020-08-15 20:07:58,954 [1] INFO HexEditApp.App - Current directory: C:\Program Files (x86)\Maxis
2020-08-15 20:07:59,006 [1] ERROR HexEditApp.MainWindow - An unhandled exception occurred: The invocation of the constructor on type 'HexEditApp.MainWindow' that matches the specified binding constraints threw an exception.

**Comment by FaithBeam** [comment]
@samboa86 Hi, can you try the previous release and see if it loads? Nothing important changed between these two releases.

https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.15.0/Sims1WidescreenPatcher.1.15.0.zip

**Comment by samboa86** [comment]
Thanks for the fast reply. Just tried it, same error

**Comment by FaithBeam** [comment]
@samboa86 Please try this release. [Sims1WidescreenPatcher.1.16.1+45119b2.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5080691/Sims1WidescreenPatcher.1.16.1%2B45119b2.zip)

I've never seen this kind of error before and googling it is kind of baffling. Nevertheless, I'm going to change some stuff up which I _think_ is related to it.

This release:
* Uses .net 4.5 instead of .net 4.0
* Removes costura.fody nuget package which combined dlls into the exe (You'll see more dlls in the zip)
* Log the stack trace as well (Something I should've done to begin with)

If it still doesn't work please post the log again. Thanks!

**Comment by samboa86** [comment]
Thanks. I tried again and got the same error, the weird thing is it isn't creating a log anymore. there is no log file

**Comment by FaithBeam** [comment]
Maybe third time is the charm? :)
In the stack trace you posted I can see the HeightTextBox_TextChanged method complaining about that the height is not in the correct format. I can only assume this means that the auto-detected screen resolution is bugging out. Try this release: 
[Sims1WidescreenPatcher.1.16.2+8c0c311.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5080945/Sims1WidescreenPatcher.1.16.2%2B8c0c311.zip)

In this I disabled detecting the screen resolution and set the default resolution to 1920x1080 (but you can change this).

**Comment by samboa86** [comment]
3rd time is a charm! It opens! But too bad I cant get the game to work... I dont know if it is because I am using the complete edition I found but when I try to patch it says "failed to find pattern" which is weird because it does create a sims backup.exe and a new sims.exe

But then opening the file the game keeps crashing after the "Maxis TM" black screen
So I dont know if it is this software or my file

**Comment by FaithBeam** [comment]
Excellent, progress! Extract this config file over the existing one and try again.
[Sims1WidescreenPatcher.exe.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5080984/Sims1WidescreenPatcher.exe.zip)

This changes the pattern the program searches for to be much more relaxed but potentially opens you up to editing the wrong bytes in the file depending on the exe you're trying to edit.

**Comment by samboa86** [comment]
It actually says it patched! this time! But now the game doesnt load at all lol. I dont even get the black Maxis screen. Man, why is this so difficult!

**Comment by FaithBeam** [comment]
@samboa86 
Are you using a nocd exe or crack? If you aren't and are running The Sims Complete Collection, use this nocd exe: http://www.gameburnworld.com/dl/dl2/m.php?p=TheSimsCompleteCollectionv1.91NoCDFixedexeEng.rar

If you are already using a nocd exe or crack follow these settings on the wiki which may solve the startup issues you're having:  https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/wiki/General-Sims-Recommendations

As for why this is so difficult, it is a little because of me ;) (unintentional I swear), running old windows games on modern windows is a pain, and you can only use the not so legal version of the game (legal exes no longer run on modern windows due to its drm).

**Comment by samboa86** [comment]
Oh man youre awesome! You keep helping me! I thought I had a nocd crack but after using that file you linked I finally got the game to load. I did it before I used your software. So then I used your software to fix the resolution and it patches but now the game looks like the picture below. tiny image giant blue space. so close!!

![Untitled](https://user-images.githubusercontent.com/40417576/90584360-71e3e880-e1a0-11ea-8d05-c8133da73bd7.png)

**Comment by FaithBeam** [comment]
Unfortunately there's no known way to enlarge the viewport of the neighborhood screens and character screens. As long as the main game looks good then the patch is working as intended.
![The Sims Complete Collection 8_19_2020 1_45_41 PM](https://user-images.githubusercontent.com/32502411/90671343-8ff22d00-e222-11ea-93af-89d24f1c2fed.jpg)
