### ISSUE TITLE
Error in StudioTown and MagicTown (UIGraphics)

### ISSUE THREAD

**Issue by heismauri** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#13]
**Installed Sims Version**
Sims 1 Complete Collection

**Are you using a nocd exe / crack?**
Cracked

**Describe the issue**
When using the original files, or modified ones Studio Town and Magic Town does not show properly

*Original files*
![Studio Town Original](https://i.imgur.com/l6QFwYR.png)
![Magic Town Original](https://i.imgur.com/CZzmMFT.png)

*Files edited from, that were found in [this reddit post](https://www.reddit.com/r/thesims/comments/6snibn/the_sims_1_widescreen_fix_1080p/)*
![Studio Town Modified](https://i.imgur.com/G2TeqXt.png)
![Magic Town Modified](https://i.imgur.com/uOCTs8U.png)

**What are the steps to reproduce the issue?**
My screenresolution 1366x768 and it just happens when when I go to those towns

**Comment by FaithBeam** [comment]
Hi @heismauri, after running my program, did you copy graphics files to your Sims installation manually? If so, you don't need to. The program will scale the images located in Content directory to the resolution you chose in the application. The images from the reddit post will not work for your resolution because those are only for 1920x1080.

**Comment by heismauri** [comment]
I am so sorry, by Original I meant the ones that were scaled up with your program. I understand it might have been confusing. And yeah the reddit post work for all of those but StarTown and MagicTown, both your program contents and the reddit ones give me that problem.

Here u have my log file
[SimsWidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5228480/SimsWidescreenPatcher.log)

**Comment by FaithBeam** [comment]
@heismauri No worry! From your log it shows that the program is not compositing pink.png over bluebackground.png and it also doesn't show it finished patching. As for those images not existing in your sims installation, don't worry, they're not part of the original game. Did you close the program before it opened a small window saying "Patched"? Resizing the images can take a while.

**Comment by heismauri** [comment]
The program closes right away, I never saw that Patched window. Could it be because it crashes? I ran the program again with a clean installation and here is my log. I also have to mention that I ran the program as an administrator.
[SimsWidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5228635/SimsWidescreenPatcher.log)

**Comment by FaithBeam** [comment]
@heismauri That is definitely crashing. Unfortunately it doesn't give us what the error is. My guess is the code I have will only capture errors on the main UI thread and since I was scaling and compositing images parallel, they weren't on the UI thread. Please try this release. I changed the program to scale images one-by-one instead of parallel which will hopefully allow the program to capture what the error is.
[Sims1WidescreenPatcher.1.17.2+0c7a8fb.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5228687/Sims1WidescreenPatcher.1.17.2%2B0c7a8fb.zip)

**Comment by heismauri** [comment]
Ok, here u have the latest log of that release
[SimsWidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5228697/SimsWidescreenPatcher.log)

**Comment by FaithBeam** [comment]
Ok, I'm stumped as to why it's not giving some sort of error in the log. In any case here is a 1366x768 images pack that you can paste into C:\Program Files (x86)\Maxis\The Sims\UIGraphics and overwrite everything. This should solve the issue of messed up Studio Town and Magic Town screens. 
[1366x768.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5228715/1366x768.zip)

**Comment by heismauri** [comment]
IT WORKED!! Thank you so so much! But still if u still need me to figure out the bug, please let me know

**Comment by FaithBeam** [comment]
@heismauri Thank you. Please try this release. It won't solve the issue but hopefully will be able to capture the exception you're getting in the log so I can do something about it. 
[Sims1WidescreenPatcher.1.17.3+2a427ef.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5231425/Sims1WidescreenPatcher.1.17.3%2B2a427ef.zip)

**Comment by heismauri** [comment]
Ok here u have my latest log. Also a little suggestion, I think it would be better if the image was overlayed on a solid color rather than upscaled. In my opinion, it will look better.
[SimsWidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5232742/SimsWidescreenPatcher.log)

**Comment by heismauri** [comment]
I was able to tweak some things and now StudioTown and MagicLand look like this, haha I couldn't put the styles in the other areas.
![Studio Town Tweaked](https://i.imgur.com/8dsRGMi.png)
I also attached my UIGraphics folder if you would like to take a look at it.
[UIGraphics.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5240651/UIGraphics.zip)

**Comment by FaithBeam** [comment]
Still no dice on that error unfortunately... :(
I just checked the Sims Creator and family selector and it seems like it is supposed to be green. Look at 800x600 vs. 1024x768 (the two default resolutions that the game has). 
![800x600](https://user-images.githubusercontent.com/32502411/93511457-d9509d80-f8f0-11ea-9cf2-6ce4d42732c1.png)
![1024x768](https://user-images.githubusercontent.com/32502411/93511467-df467e80-f8f0-11ea-8e0b-70935a50a031.png)

That's actually a really smart idea with overlaying the default graphic over the blue background! When I get some time, I'll work on that.

**Comment by heismauri** [comment]
Yeah, I got the default graphic from a screenshot so (I suppose) it is not very hq. Still works tho. Yay can't wait for u to add that default graphic because it looks nice. Also, what a boomer about the green background, it looks weird. It is what it is tho. Thanks.

**Comment by FaithBeam** [comment]
@heismauri Hello! I've added your suggestion in #14, and I've added an extra attempt to catch and log the error you are getting in this release: 
[Sims1WidescreenPatcher.1.18.1.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5250026/Sims1WidescreenPatcher.1.18.1.zip)

If this doesn't work like previously, here is a zip containing the new graphics :) 
[1366x768.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5250029/1366x768.zip)

**Comment by heismauri** [comment]
I'm glad that u liked my suggestion and even implemented it! The largeback.bmp has one pixel off so I fixed it here.
[dlgframe-largeback.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5250628/dlgframe-largeback.zip)

Also, here is my latest log, no error info still
[SimsWidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5250632/SimsWidescreenPatcher.log)

**Comment by FaithBeam** [comment]
Well that's a bummer about the logs... I'm kind of confused at the largeback.bmp because that is the image from my UIGraphics.far file. I agree that your largeback.bmp looks better when opening the image in a photo editor but does it make any visible impact in game? I can't see anything from my game. I'm hesitant to add this because I'd eventually like to go to extracting bmps from the UIGraphics.far with my [Sims.Far](https://github.com/FaithBeam/Sims.Far) library instead of providing bmps. I checked my UIGraphics.far with [FarEdit](https://www.fileplanet.com/archive/p-76076/FAR-Edit) and it got the same result as my extracted largeback.bmp so I'm not sure of the benefit.

![largeback](https://user-images.githubusercontent.com/32502411/93819505-ccea7e80-fc29-11ea-8cb4-9ee67bccd783.jpg)

**Comment by FaithBeam** [comment]
If you feel up to trying another release, please try this one: 
[Sims1WidescreenPatcher.1.18.2+e22e479.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5263790/Sims1WidescreenPatcher.1.18.2%2Be22e479.zip)

If that still doesn't create a stacktrace in the log file, please check the your Event Viewer. You would open Event Viewer > Windows Logs > Application > Probably the most recent .NET Runtime
It would look something like this: ![Event Viewer 9_22_2020 4_06_13 PM-or8](https://user-images.githubusercontent.com/32502411/93932199-cf161100-fced-11ea-8ad0-1801b7a07da6.png)

**Comment by heismauri** [comment]
Weird that the original UIGraphics has one pixel off, well it is what it is. Is in that faredit info about the green screen in the family selector?

Here u have both logs and errors.
[SimsWidescreenPatcher(Win+Log).zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5264501/SimsWidescreenPatcher.Win%2BLog.zip)

**Comment by FaithBeam** [comment]
The closest thing relating to the green screen I saw in the files is CreateACharBack.bmp 
![CreateACharBack](https://user-images.githubusercontent.com/32502411/94200414-61521c80-fe88-11ea-9906-be844fc1f723.png)
As you can see, no green so I assume the game fills the empty space with green for whatever reason. Resizing this file doesn't do anything sadly.

As for the error you're getting, System.AccessViolationException, that can't be handled normally because something really bad happened with the application. The error does have references to System.Threading.Tasks.Parallel because I added Parallel.Foreach back after you tested without because you were still getting an error. 

This update:
* Uses error handling specific to System.AccessViolationException
* Removes Parallel.Foreach (again)
* Updates Magick.NET to v7.22.0 from v7.21.1
* Targets x86 instead of AnyCPU (grapsing at straws here)

If the stacktrace is not in the log, would you get the Event Viewer log again please? https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.18.3/Sims1WidescreenPatcher.1.18.3+0f4f6d4.zip

**Comment by heismauri** [comment]
IT WORKED! Thank youuuuu. It is such a boomer tho about the green screen. But thank you also for taking a further look into it. Thank you thank you. It worked!

**Comment by FaithBeam** [comment]
That's awesome! I don't actually know which of the changes fixed it though. Would you be willing to test one more time please? This time I need you to tell me which of these three releases **fails**

* https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.18.5-features-hotfix-13-parallel/Sims1WidescreenPatcher.1.18.5-features-hotfix-13-parallel+adf3f16.zip
* https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.18.5-features-issue-13-magicknet/Sims1WidescreenPatcher.1.18.5-features-issue-13-magicknet+6bd0636.zip
* https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.18.5-features-issues-13-anycpu/Sims1WidescreenPatcher.1.18.5-features-issues-13-anycpu+30d8875.zip

**Comment by heismauri** [comment]
✅ parallel
✅ magicknet
✅ anycpu
The 3 versions worked just fine.
Also, I upscaled each image to 16:9 so when the program upscales them it doest stretched them, hope you like them.
[16-9loadscreens.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5285553/16-9loadscreens.zip)

**Comment by FaithBeam** [comment]
Hello, it's been a while! Sorry for the delay, but I was a little sad and unmotivated because all three of those versions worked when I was expecting at least one to fail. Anyway, I implemented your proposed changes to the loadscreens in [1.19.0](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.19.0/Sims1WidescreenPatcher.1.19.0+x86.zip). Give it a try if you like!
