### ISSUE TITLE
Screen not centered?

### ISSUE THREAD

**Issue by CaveJohnson95** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#28]
**Installed Sims Version**
Sims 1 Complete Collection

**Are you using a nocd exe / crack?**
Yes

**Describe the issue. Include screenshots if you can**
Image is attached, the Screen is not centered after Patching

https://user-images.githubusercontent.com/84499302/118942854-643bd900-b953-11eb-9af9-d1bbe7963d77.jpg

**What are the steps to reproduce the issue?**
Fresh Sims 1 Install and Patching afterwards

**Please attach the generated log file [SimsWidescreenPatcher.log**](

)

**Comment by CaveJohnson95** [comment]
I figured out what caused the problem, i'm on a laptop and had zoom set to 125 %, setting it to 100 % fixes the problem, is there any way to fix this?

**Comment by FaithBeam** [comment]
@CaveJohnson95 

I've seen something similar with #10. He was able to solve it by uninstalling my patch then patching again. The scaling setting is interesting because I've played at 125%-200% scaling with no issue. In case scaling is the issue, I believe you can disable it through the shortcut so you don't have to set it to 100% system wide.

![image](https://user-images.githubusercontent.com/32502411/119121464-74a78e80-b9fb-11eb-95da-a5263f5c4edf.png)
![image](https://user-images.githubusercontent.com/32502411/119121517-84bf6e00-b9fb-11eb-898d-ad2dc8e5d7d8.png)

**Comment by CaveJohnson95** [comment]
With the override high DPI scaling behavior the game is displayed correctly. Perfect. Thanks for your help!

**Comment by FaithBeam** [comment]
Cool, glad that solved it :)
