### ISSUE TITLE
no background music after installing widescreen patch

### ISSUE THREAD

**Issue by spidy314** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#41]
**Installed Sims Version**
Sims 1 Complete Collection

**Are you using a nocd exe / crack?**
yes
**Describe the issue. Include screenshots if you can**
hi guys, just wanting to let you know with the current iteration on the widescreen patcher, the background music (like neighborhood or buy/build) just dont seem to be working and it works when its unpatched.
**What are the steps to reproduce the issue?**
whenever i install the patch, i have tried no wrapper, as well as the two optional ones

**Comment by FaithBeam** [comment]
@spidy314 Can you zip your unpatched sims.exe (Sims Backup.exe), patched Sims.exe (Sims.exe), and patch log (Simswidescreenpatcher.log) files and upload them here please?

**Comment by spidy314** [comment]
[Sims1stuff.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/7358484/Sims1stuff.zip)
here you go :)

**Comment by FaithBeam** [comment]
@spidy314 I see what's going on. You're using a cracked exe that's already been patched for 1920x1080 resolution. The way my patch works is not compatible in this situation. My program searches for a pattern of bytes that signify the resolution 800x600. Technically is just searches for bytes representing 800 followed by 600. Since these bytes have already been changed in your Sims exe, my program skips over where it would normally change them and finds the next 800 followed by 600 pattern and changes that. Essentially my program just changed random bytes in that exe. There's not really a way I can account for this with this style of patching.

Here's what you should do:
* Run my patch and click uninstall if it isn't already to clean everything out so you're in a mostly vanilla state
* Download a crack for the sims complete collection that hasn't already been patched to a custom resolution
  * [PleasantSims](https://pleasantsims.com/sims-1-widescreen-windowed/) has a link to it
* Use the new exe to overwrite your existing sims exe
* Run my program again and patch the new exe

I'll update the Readme pointing out to only use unpatched cracked exes. Let me know if this works for you.
