### ISSUE TITLE
"'NativeMagickSettings' threw an exception" on Legacy ver

### ISSUE THREAD

**Issue by yxles-dev** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#53]
**Installed Sims Version**
The Sims 1 Complete Collection

**Are you using a nocd exe / crack?**
Yes

**Describe the issue. Include screenshots if you can**
Running the patcher on Windows XP threw a error stating "An unhandled exception occurred. The type initializer for 'NativeMagickSettings' threw an exception"
![untitled](https://user-images.githubusercontent.com/84117528/175827316-2fdd48a4-870f-4ba9-bb67-5ac967633277.jpg)

**What are the steps to reproduce the issue?**
Simply run the program and click patch

**Please attach the generated log file SimsWidescreenPatcher.log**
[SimsWidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/8987171/SimsWidescreenPatcher.log)

**Comment by FaithBeam** [comment]
@yxles-dev Sorry for the late reply. It turns out my patcher never worked for Windows XP despite me believing it would because it targeted .NET Framework 4.0. There's some sort of issue with Magick.NET and very old operating systems. This is the main issue from your log
`ERROR SimsWidescreenPatcher.App - System.DllNotFoundException: Unable to load DLL 'Magick.Native-Q8-x86.dll': The specified procedure could not be found.`

Googling around leads me [here](https://stackoverflow.com/questions/63274585/imagemagick-unable-to-load-dll-magick-native-q8-x86-dll) which wants me to do dllimports. Truthfully, I don't want to put the effort in this for Windows XP, but if someone wants to figure this out I'd accept a PR. I'll remove the -legacy branch from the releases page.

**Comment by FaithBeam** [comment]
@yxles-dev 
I've released a new legacy branch version that should work for you https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/1.24.0-legacy

I've tested this on a Windows XP machine and it does work. https://www.youtube.com/watch?v=qrBMkBbevt4
