### ISSUE TITLE
Running on MacOS

### ISSUE THREAD

**Issue by JMonster973** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#56]
I am completely new to all of this and I was wondering if there is any way to get the Sims 1 Complete Collection Running on MacOS with this patch. Is there anything else I need to install besides this to get it to work? Thanks!

**Comment by FaithBeam** [comment]
@JMonster973 This patch is only to make The Sims widescreen (or any resolution you want). It doesn't do anything to make it run on newer systems. That said, here's a video that shows how to install The Sims with Wineskin Winery and apply the patch on macOS: https://www.youtube.com/watch?v=hOy1boR1_Go

**Comment by JMonster973** [comment]
Thank you so much. I followed this tutorial and it worked. There are a few minor glitches in the game but otherwise it plays very nicely. All of the text on the screen is very small though. Are there any other resolutions you would recommend? Also, if you don't mind me asking: How did you find this tutorial? Before this, I looked for hours and couldn't find one.

**Comment by JMonster973** [comment]
Thank you so much. I followed this tutorial and it worked. There are a few minor glitches in the game but otherwise it plays very nicely. All of the text on the screen is very small though. Are there any other resolutions you would recommend? Also, if you don't mind me asking: How did you find this tutorial? Before this, I looked for hours and couldn't find one. (Please ignore the two times I closed this above. Those were accidental)

**Comment by FaithBeam** [comment]
I like to stick to resolutions between 720p and 1080p for the reason you said. On my MBP, I choose 1312x848. You can find which resolutions would be good by:
1. Opening Displays
2. Click Scaled
3. Hover (Don't click) over the different scaling options to show their resolutions
4. Enter/select that resolution in the patcher
![resolutions](https://user-images.githubusercontent.com/32502411/184497115-6167f781-5016-422d-909b-fd8b66e337c4.jpg)
![patcher](https://user-images.githubusercontent.com/32502411/184497120-0bd2a756-4a45-46ed-bfdc-76f4720e7338.jpg)

I created that video in response to this issue. ;) There was a previous video that I liked to link but it was taken down probably because he linked to a download of The Sims. I'm hoping that by not linking to it, the video will stay up. Who knows.

**Comment by JMonster973** [comment]
Thank you so much. This worked perfectly.
